# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"genre_cols": "01_features_store.ipynb",
         "genre_and_title_cols": "01_features_store.ipynb",
         "dot_product_similarity": "02_similarities.ipynb",
         "similarity": "02_similarities.ipynb",
         "get_most_similar": "03_recommendation.ipynb",
         "get_recommendations": "03_recommendation.ipynb"}

modules = ["features_store.py",
           "similarities.py",
           "recommendation.py"]

doc_url = "https://pyth314.github.io/moviesrec/"

git_url = "https://github.com/pyth314/moviesrec/tree/master/"

def custom_doc_links(name): return None
