# AUTOGENERATED! DO NOT EDIT! File to edit: mle-2020/01_features_store.ipynb (unless otherwise specified).

__all__ = ['genre_cols', 'genre_and_title_cols']

# Cell
import pandas as pd

try :
    users = pd.read_csv("data/users.csv")
    movies = pd.read_csv("data/movies.csv")
    ratings = pd.read_csv("data/ratings.csv")
except :
    users = pd.read_csv("/Users/pierre-yvesthumerel/Desktop/kaggle/_interview/mle-2020/mle-2020/data/users.csv")
    movies = pd.read_csv("/Users/pierre-yvesthumerel/Desktop/kaggle/_interview/mle-2020/mle-2020/data/movies.csv")
    ratings = pd.read_csv("/Users/pierre-yvesthumerel/Desktop/kaggle/_interview/mle-2020/mle-2020/data/ratings.csv")

# Cell
genre_cols = ["Animation", "Children's",
       'Comedy', 'Adventure', 'Fantasy', 'Romance', 'Drama',
       'Action', 'Crime', 'Thriller', 'Horror', 'Sci-Fi', 'Documentary', 'War',
       'Musical', 'Mystery', 'Film-Noir', 'Western']

genre_and_title_cols = ['title'] + genre_cols