# AUTOGENERATED! DO NOT EDIT! File to edit: mle-2020/01_similarities.ipynb (unless otherwise specified).

__all__ = ['dot_product_similarity', 'similarity']

# Cell
from  moviesrec.features_store import movies , genre_and_title_cols , genre_cols

# Cell
dot_product_similarity = lambda data  : data.values.dot(data.values.T)

# Cell
similarity=dot_product_similarity(movies[genre_cols])